name: quotevault
description: "A new Flutter project."
publish_to: "none"
version: 1.0.2+24

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_dotenv: ^5.1.0
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  screenshot: ^3.0.0
  http: ^1.6.0
  flutter_local_notifications: ^19.5.0
  shared_preferences: ^2.5.4
  timezone: ^0.10.1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.3
  shimmer: ^3.0.0
  flutter_animate: ^4.5.2
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  firebase_messaging: ^16.1.1
  cloud_firestore: ^6.1.2
  font_awesome_flutter: ^10.12.0
  image_picker: ^1.2.1
  firebase_storage: ^13.0.6
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  awesome_snackbar_content: ^0.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "assets/icon/app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon/app_logo.png
